* tianji2014
** tmp
** cupl
*** Q
**** 概述
验证： 检查api-key及ip地址，确定是否有访问权限
list: 只获取该学校发布的非外部来源下的记录
新增: 自动设置外部来源标识、对应用户及对应学校（根据api-key确定对应学校及标识）
更新：只有执行新增操作的对应用户才能更新对应记录
文档地址: /docs/openapi1
代码分支：school_certify

问题：
1、操作用户id（uid）如何对应（uid需为天际用户id）： RE：不需传入uid，使用对应学校的管理员用户id
2、某些字段（key-value列表,如城市、分类）的存储值如何处理。： RE：设置默认值
   活动：类型/付费方式/城市 
   新闻：分类id/推荐分类id

**** 存id的字段如何对应？ 只设默认值
*** frontpage
**** login pop
http://192.168.3.4/new_companies/schoolPage/schoolLayer.php
*** API
**** auth
api-key
ip


**** 活动 events
source: cupl

***** event_category 3
[[1, "沙龙讲座"], [2, "会议展览"], [3, "教育培训"], [4, "交友聚会"], [5, "艺术文化"], [6, "运动旅行"], [7, "社会公益"], [8, "消费体验"], [9, "其他"]]
***** fee_type 2
  FEE_TYPES={
    0 => "免费",
    1 => "付费",
    2 => "按实际费用AA制"
  }

***** city 1
[[1, "北京"], [2, "上海"], [3, "广州"], [4, "深圳"]]

**** 新闻资讯 articles

***** article_category_id
***** recommend_category_id
**** 职场心得 job_experiences
**** 雇主反馈 employer_feedbacks
***** corp_id corp_name
**** 职位
***** 推荐职位 GET http://10.40.5.53/job-rest/user/39774645/pymk/2,2
{
  "items": [
    {
      "companyId": 40548,
      "city": "北京",
      "companyName": "翰林经纬科技(北京)有限公司",
      "workYear": 3,
      "salaryFrom": 2000,
      "salaryTo": 2000,
      "province": 11,
      "positionEnum": 5,
      "welfare": "",
      "name": ".net软件工程师(Senior)",
      "field": 104,
      "id": 28244,
      "country": "CN",
      "description": "u  参与公司医疗系统的开发；\nu  负责现有系统的维护和功能需求的添加修改；\nu  负责公司其他日常开发任务。\n\ru  计算机相关专业专科以上学历，两年及其以上C#开发经验，有两个及其以上大型项目经验者  优先；\nu  精通c#，熟悉c# windows c/s模式程序开发；\nu  能使用DEVEXPRESS第三方控件者优先\nu  具备一定的面向对象分析设计能力；\nu  熟悉Sqlserver数据库开发；\nu  精通SQL语句，了解存储过程编写；\nu  熟练使用LINQ；熟练使用 VS2008 等开发工具；\nu  熟悉.NET 框架，有较强的逻辑思维能力，精通三层架构；\nu  具备规范化、标准化的代码编写习惯和良好的技术文档习惯；\nu  兴趣编程，沟通能力强。"
    },
    {
      "companyId": 224105,
      "city": "北京",
      "companyName": "北京智慧盛达科技有限公司",
      "workYear": 4,
      "salaryFrom": 4000,
      "salaryTo": 8000,
      "province": 11,
      "positionEnum": 5,
      "welfare": "五险 补助",
      "name": "软件工程师（LotusDomino/Notes）",
      "field": 104,
      "id": 29948,
      "country": "CN",
      "description": "职位描述：  \n\n1. 参与了解项目的需求分析. 需求设计以及系统设计； \n\n2. 按项目要求完成模块详细设计和编程实现；\n\r职位要求： \n\n1. 2年左右Lotus Notes开发经验； \n\n2. 精通Domino/Notes技术体系； \n\n3. 精通工作流系统原理，体系架构，有引擎系统开发经验； \n\n4. 熟练掌握Domino Web开发相关技术，如xpage，JavaScript，HTML，CSS等等； \n\n5. 熟悉Lotus系列软件产品的应用集成和开发，有大型OA系统开发管理经验者优先。"
    }
  ],
  "itemAmount": 2
}

***** 职位详情 GET http://rest/job-rest/position/{id}
GET http://10.40.5.53/job-rest/position/28244

    {
       "items":
       [
           {
               "companyId": 40548,
               "city": "北京",
               "companyName": "翰林经纬科技(北京)有限公司",
               "workYear": 3,
               "salaryFrom": 2000,
               "salaryTo": 2000,
               "province": 11,
               "positionEnum": 5,
               "welfare": "",
               "name": ".net软件工程师(Senior)",
               "field": 104,
               "id": 28244,
               "country": "CN",
               "description": "u 参与公司医疗系统的开发； u 负责现有系统的维护和功能需求的添加修改； u 负责公司其他日常开发任务。 u 计算机相关专业专科以上学历，两年及其以上C#开发经验，有两个及其以上大型项目经验者 优先； u 精通c#，熟悉c# windows c/s模式程序开发； u 能使用DEVEXPRESS第三方控件者优先 u 具备一定的面向对象分析设计能力； u 熟悉Sqlserver数据库开发； u 精通SQL语句，了解存储过程编写； u 熟练使用LINQ；熟练使用 VS2008 等开发工具； u 熟悉.NET 框架，有较强的逻辑思维能力，精通三层架构； u 具备规范化、标准化的代码编写习惯和良好的技术文档习惯； u 兴趣编程，沟通能力强。"
           }
       ],
       "pageAmount": 1,
       "itemAmount": 1,
       "currentPage": 1
    }

***** 最新职位 GET http://rest/job-rest/positions/{page},{count}
GET http://10.40.5.53/job-rest/positions/1,10

{
  "items": [
    {
      "city": "北京",
      "companyName": "中矿澳亚(北京)矿业咨询有限公司",
      "workYear": 6,
      "salaryFrom": -1,
      "province": 11,
      "diploma": 1,
      "positionEnum": 1,
      "recruitNumber": 1,
      "welfare": "",
      "name": "高级财务经理",
      "field": 1201,
      "id": 41829,
      "country": "CN",
      "description": "工作职责： 1、此职位系高级管理职位，不参与财务日常核算工作。 2、完善财务部门组织架构，负责从会计基础工作规范、会计核算、财务信息系统、会计档案、授权、资金、结算、资产、税收、内部审计等方面建立系统、全面、完整的企业财务管理制度，涵盖财务核算体系和财务监控体系，完善财务实务操作规范。 3、负责凭证审核，财务报表以及纳税申报表的审核，向公司决策层提交财务管理工作报告。 4、负责组织开展投资确认工作，审核投资确认资料的真实性、完整性，保障股东利益。 5、负责公司资金管理，监督重大资金流向。 6、建立并完善财务报表体系，尤其是三大报表之外的单项子报表体系。 7、定期对财务账务进行内部审计，对于审计发现的问题提出建议或意见。 8、定期对财务各个岗位的工作进行检查和指导，确保企业财务管理制度切实贯彻到财务各个岗位的日常工作中。 9、负责财务人员的招聘、培训、考核等工作。 10、负责维护公司进出口资质、外管局资质等工作。 11、协调公司同银行、工商、税务、外管局等政府部门的关系，维护公司形象和公司利益。 任职资格： 1、会计、金融、经济等相关专业大专或以上学历，8年以上大型企业集团财务管理工作经验。 2、精通国家《会计基础工作规范》、《企业会计准则》、《企业会计制度》、《税收法规》、《外贸法规》、《外汇管理政策》等相关法律法规规定。 3、以往有系统、全面、完整建立企业财务管理制度的工作经历和成功经验。 4、具有丰富的财务管理工作经验。 5、具有良好的口头表达能力和文字表达能力。 6、具有较强的判断和决策能力、人际沟通和协调能力、计划与执行能力。 7、工作态度细致、严谨。 8、具有较高的工作热情和责任感。"
    },
    {
      "city": "北京",
      "companyName": "品今(北京)资产管理有限公司",
      "workYear": 5,
      "salaryFrom": -1,
      "province": 11,
      "diploma": 1,
      "positionEnum": 3,
      "recruitNumber": 1,
      "welfare": "",
      "name": "产品总监（资产管理）",
      "field": 0,
      "id": 41828,
      "country": "CN",
      "description": "招聘条件： 1、工商财经类、金融工程、数学相关专业本科以上学历优先考虑 2、有信托公司、三方理财公、券商资管、私人银行产品部门相关经验者优先 3、对市场、各类金融产品有独到的个人见解 职位职能： 1、统筹负责公司产品部门事务 2、负责制定公司产品结构、策略、风控体系 3、负责统筹产品研发、包装、发行、培训事宜 4、负责开拓产品渠道、销售渠道等 公司介绍： 专注于为中国高净值人士、富有家族、以及机构投资人量身打造全方位的财富管理及资产管理服务。通过严格的风险控制体系、产品设计、及产品筛选体系，为客户进行全方位的资产配置，根据客户的需求，从独立、客观、专业的角度，为高净值人群提供横跨信托、公募基金、私募基金、一级市场、二级市场、境外主要市场、地产基金、PE私募股权基金、艺术品投资基金等资本市场的理财配置方案。助力高端客户实现资产保值增值的目标。       不远的将来，品今资管将成为中国高端财富管理、资产管理的第一选择"
    }
  ],
  "pageAmount": 1416,
  "itemAmount": 2832,
  "currentPage": 1,
  "hasNext": true
}

***** message

推荐职位接口

URL:http://rest/job-rest/user/{userId}/pymk/{page},{count}

METHOD:GET

职位详情主要是用在政法大学。
在 2014年3月12日，上午10:05，fengzhenxing <fengzhenxing@tianji.com> 写道：

> Hi 国栋：
>
> 1、最新职位接口
>
> method:GET
> URL:http://rest/job-rest/positions/{page},{count}
>
> 2、职位详情接口
>
> method:GET
> URL:http://rest/job-rest/position/{id}
>
> 40-5已部署最新。
>

**** login
/schools/ajax/login
跨域调用  只需知道execA.html的链接
http://blog.csdn.net/fdipzone/article/details/17619673
iframe:
  // exec main function  
  function exec_main(){  
    if(typeof(exec_obj)=='undefined'){  
        exec_obj = document.createElement('iframe');  
        exec_obj.name = 'tmp_frame';  
        exec_obj.src = 'http://localhost/execA.html';  
        exec_obj.style.display = 'none';  
        document.body.appendChild(exec_obj);  
    }else{  
        exec_obj.src = 'http://localhost/execA.html?' + Math.random();  
    }  
  }  
execA.html:
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">  
    <html>  
     <head>  
      <meta http-equiv="content-type" content="text/html; charset=utf-8">  
      <title> exec main function </title>  
     </head>  
      
     <body>  
        <script type="text/javascript">  
            parent.parent.fMain(); // execute main function  
        </script>  
     </body>  
    </html>  

*** call api
接口地址：
1、职场心得
http://localhost/api/experience.json
参数为array('title' => '标题', 'info' => '正文')

2、活动
http://localhost/api/event.json
参数array('title' => '标题', 'info' => '正文', 'starttime' => '开始时间', 'endtime' => '结束时间', 'location' => 活动地点

3、新闻
http://localhost/api/news.json
参数为array('title' => '标题', 'info' => '正文')
*** tmp
**** TODO 1 推荐职位 修改原来的推荐方案。按照月薪1w 以上（通过传递参数来调用，并按照薪水倒序） 来推荐职位。 James  在周二给提供出API

NOTE： ？？这个是对应原来的哪个接口的修改：最新职位还是个人职位推荐

查询开始月薪以上的职位，并且按照开始月薪排序到排序的接口已经提供。并且部署上去了。

method:get
URL:http://rest/job-rest/positions/{salaryFrom}/1,10

**** TODO    2 和政法大学用户绑定信息在今晚给我们产品方案（Liz）。 @xingxing 会在周三上午提供好接口。
Note：?? account form 结构，新建用户密码的传出，以发送密码邮件

今天xingxing提出那边会提供用户绑定接口，但页面还需要B端自行完成；
            前端页面已切完：http://192.168.3.4 /new_companies/schoolPage/schoolLayer.php；
            不确定这个弹窗应该加在哪个页面中。
      BD branch: zf_api@BD
      
登录
params[:account][:email_or_mobile] --手机或邮箱
params[:account][:password] --密码.

params=> {"account"=>{"email_or_mobile"=>"sdsdf@diei.com",
"password"=>"123123"},}

注册

params=>
{ "company"=>
{"position"=>"程序员",----职位名称
"name"=>"天际网",----所在公司},
"account"=>
{"name_native_display"=>"dsiei ddfie",----姓名
"email_or_mobile"=>"dsiei@sdiei.com"，------邮箱
"gender"=>"m",----性别（m=男，f=女）
}
"zf"=>
{ "id"=>"1"---政法大学传过来的ID
 （其他政法传过来需要存的东西都可以写在这里）
}
}


          commit cec70410d5eacc9581f670b1fa8283e4776d6125
Merge: f45fc19 83e961d
Author:     sjm <shangjingmin@tianji.com>
AuthorDate: Tue Mar 18 14:45:04 2014 +0800
Commit:     sjm <shangjingmin@tianji.com>
CommitDate: Tue Mar 18 14:45:04 2014 +0800

    Merge branch 'zf_api@BD' into school_certify

 app/controllers/account/ajax_controller.rb  |   55 +++++++++++++++++++++++++++
 app/models/account.rb                       |    1 +
 app/models/background.rb                    |    2 +-
 app/models/zf_info.rb                       |    5 +++
 config/routes/account.rb                    |    3 ++
 db/migrate/20140317062058_create_zf_info.rb |   12 ++++++
 6 files changed, 77 insertions(+), 1 deletion(-)

**** TODO   3 邀请好友,@MingLI 会在周二调试好。
**** TODO   4 MBA 认证图 显示在profile 等。等待C端产品确定。
**** DONE 5 老师邀请：需要设计三个TAB，周一给我们相关设计。 RE： 产品说暂时不做了？？我让徐前回复那封邮件了，单我尚未收到回复邮件。
CLOSED: [2014-03-18 Tue 15:13]
- State "DONE"       from "TODO"       [2014-03-18 Tue 15:13]

**** TODO  6  邀请弹出框落地。一 潜在学员完成报名 弹出， 二 邀请函点击关注时候 弹出。
**** DONE 7  绑定政法大学用户 密码邮件模板 @Liz  周一上午给设计出
CLOSED: [2014-03-18 Tue 15:14]
- State "DONE"       from "TODO"       [2014-03-18 Tue 15:14]
Note: html代码已切，？？图片不确定放在前端的哪个目录下
**** DONE 8  MBA 职业发展频道右侧有文档需要下载。（产品待确定报告文档，我们先做成下载方式）
CLOSED: [2014-03-18 Tue 15:15]
- State "DONE"       from "TODO"       [2014-03-18 Tue 15:15]
Note: 现在不用放入口。是以后学员数据进来了，再给老师做数据分析报告的文档。（已安排书祥删除入口）

** oAuth
http://blog.csdn.net/seccloud/article/details/8192707
http://zhuyonghui116.blog.hexun.com.tw/67962330_d.html
http://djb4ke.iteye.com/blog/683153

https://github.com/songkick/oauth2-provider/tree/master/example

[[/home/sjm/nethd/book/comp/oauth/OAuth_2.0.pdf][OAuth_2.0]

client_id 	3so49oyi8vkdiru4ygogl6kz6rg9dyb
client_secret 	hhkju7a2ra3xmsnyjafg740l04518ge

localhost:9292/oauth/authorize?response_type=token&client_id=3so49oyi8vkdiru4ygogl6kz6rg9dyb&redirect_uri=http%3A%2F%2Fwww.sjm.com:3000%2Fcorps1&scope=read_notes
localhost:9292/oauth/authorize?response_type=code&client_id=3so49oyi8vkdiru4ygogl6kz6rg9dyb&redirect_uri=http%3A%2F%2Fwww.sjm.com:3000%2Fcorps1&scope=read_notes
localhost:9292/oauth/authorize?code=&clien&client_id=3so49oyi8vkdiru4ygogl6kz6rg9dyb&redirect_uri=http%3A%2F%2Fwww.sjm.com:3000%2Fcorps1&scope=read_notes

p1= {client_id: '3so49oyi8vkdiru4ygogl6kz6rg9dyb', client_secret: "hhkju7a2ra3xmsnyjafg740l04518ge", redirect_url: "http://www.sjm.com:3000/corps1"}
p2 = {grant_type: "authorization_code"}
{code: params[:code]}.merge(p1.merge(p2))
a = RestClient.post("http://localhost:9292/oauth/authorize", {code: params[:code]}.merge(p1.merge(p2)))

** tfs/hadoop
*** Q
**** no file name for put
版本：
sjm@sjm-tj:~/nethd/prj/tfs$ svn info
Path: .
Working Copy Root Path: /home/sjm/nethd/prj/tfs
URL: http://code.taobao.org/svn/tfs/branches/dev_for_outer_users
Repository Root: http://code.taobao.org/svn/tfs
Repository UUID: b722c2b5-6a69-4643-bcd1-1a75825fa998
Revision: 2805
Node Kind: directory
Schedule: normal
Last Changed Author: linqing
Last Changed Rev: 2750
Last Changed Date: 2014-01-04 22:54:28 +0800 (Sat, 04 Jan 2014)


操作：
TFS> lsf 101
[2014-02-21 15:27:35] DEBUG base_packet_factory.cpp:48 [139708583184256] pcode: 2, length: 12
[2014-02-21 15:27:35] DEBUG base_packet_factory.cpp:48 [139708583184256] pcode: 14, length: 12
FileList Size = 3

T19RETByhT1RCvBVdK
T19RETByxT1RCvBVdK
T19RETByZT1RCvBVdK
Total : 3 files
TFS> put orgguide.pdf
[2014-02-21 15:33:22] DEBUG base_packet_factory.cpp:48 [139708583184256] pcode: 2, length: 12
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:118 [139708583184256] tfs open success: get block info success, blockid: 101, fileid: 0, mode: 2, ret: 0
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:818 [139708583184256] create file start, client: 0xadd120, index: 0, blockid: 101, fileid: 0
[2014-02-21 15:33:22] DEBUG base_packet_factory.cpp:48 [139708583184256] pcode: 21, length: 12
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:755 [139708583184256] do request success. client: 0xadd120, index: 0, phase: 1, ret: 0, blockid: 101, fileid: 0, offset: 0, size: 0, crc: 0, inneroffset: 0, filenumber: 0, status: 1, rserver: 192.168.3.34:8200, wserver: 192.168.3.34:8200.
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:588 [139708583184256] send packet. request size: 1, successful request size: 1
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:668 [139708583184256] get success response. client id: 0xadd120, request size: 1, get response size: 1
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:883 [139708583184256] create file name rsp. blockid: 101, fileid: 5, filenumber: 2450987374532886531
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:803 [139708583184256] do response success. index: 0, phase: 1, ret: 0, blockid: 101, fileid: 5, offset: 0, size: 0, crc: 0, inneroffset: 0, filenumber: 2450987374532886531, status: 2, rserver: 192.168.3.34:8200, wserver: 192.168.3.34:8200.
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:914 [139708583184256] tfs write data start, blockid: 101, fileid: 5, size: 399341, offset: 0
[2014-02-21 15:33:22] DEBUG base_packet_factory.cpp:48 [139708583184256] pcode: 9, length: 36
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:755 [139708583184256] do request success. client: 0xadd120, index: 0, phase: 2, ret: 0, blockid: 101, fileid: 5, offset: 0, size: 399341, crc: 0, inneroffset: 0, filenumber: 2450987374532886531, status: 2, rserver: 192.168.3.34:8200, wserver: 192.168.3.34:8200.
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:588 [139708583184256] send packet. request size: 1, successful request size: 1
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:668 [139708583184256] get success response. client id: 0xadd120, request size: 1, get response size: 1
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:964 [139708583184256] tfs write data success, crc: 4006393245, offset: 0, size: 399341
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:803 [139708583184256] do response success. index: 0, phase: 2, ret: 0, blockid: 101, fileid: 5, offset: 0, size: 399341, crc: -288574051, inneroffset: 0, filenumber: 2450987374532886531, status: 3, rserver: 192.168.3.34:8200, wserver: 192.168.3.34:8200.
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:301 [139708583184256] write success, offset: 0, size: 399341, segment count: 1
[2014-02-21 15:33:22] DEBUG base_packet_factory.cpp:48 [139708583184256] pcode: 10, length: 44
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:755 [139708583184256] do request success. client: 0xadd120, index: 0, phase: 3, ret: 0, blockid: 101, fileid: 5, offset: 0, size: 0, crc: -288574051, inneroffset: 0, filenumber: 2450987374532886531, status: 3, rserver: 192.168.3.34:8200, wserver: 192.168.3.34:8200.
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:588 [139708583184256] send packet. request size: 1, successful request size: 1
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:668 [139708583184256] get success response. client id: 0xadd120, request size: 1, get response size: 1
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:1051 [139708583184256] tfs file close success, dsip: 192.168.3.34:8200
[2014-02-21 15:33:22] DEBUG tfs_file.cpp:803 [139708583184256] do response success. index: 0, phase: 3, ret: 0, blockid: 101, fileid: 5, offset: 0, size: 0, crc: -288574051, inneroffset: 0, filenumber: 2450987374532886531, status: 4, rserver: 192.168.3.34:8200, wserver: 192.168.3.34:8200.
put orgguide.pdf =>  success.
TFS> lsf 101
[2014-02-21 15:33:25] DEBUG base_packet_factory.cpp:48 [139708583184256] pcode: 2, length: 12
[2014-02-21 15:33:25] DEBUG base_packet_factory.cpp:48 [139708583184256] pcode: 14, length: 12
FileList Size = 4

T19RETByhT1RCvBVdK
T19RETByxT1RCvBVdK
T19RETByZT1RCvBVdK
T19RETBydT1RCvBVdK
Total : 4 files
**** how to get file and trans to ruby File
*** install
http://www.cnblogs.com/zhy113/archive/2013/03/20/2971267.html TFS编译-----------唉，淘宝的这个开源真是垃圾到极点了。这帮工程师都他妈在吃屎！
*** tip
**** Open3.capture3: return: info error status
** gem clean 20140201
*** sjm
**** gem 'best_in_place', ‘2.1.0'
https://github.com/bernat/best_in_place

sjm@sjm-tj:~/nethd/tianji/tianjicom$ git grep -i best_in_place
Gemfile:gem 'best_in_place', '2.1.0'
app/views/profile/_p_top.html.erb:  $('.best_in_place')
app/views/profile/_p_top.html.erb:  .best_in_place()
app/views/profile/_p_top.html.erb:  .live("best_in_place:activate", function() {
app/views/profile/_p_top.html.erb:  <span><%= best_in_place @account, :mobile_nu
app/views/profile/_p_top.html.erb:      <span><%= best_in_place work, :url, :pat
app/views/profile/_p_top.html.erb:      <span><%= best_in_place work, :start_dat
app/views/profile/_p_top.html.erb:      <span><%= best_in_place work, :end_date,
app/views/profile/_p_top.html.erb:      <span><%= best_in_place work, :detail, :
(END)



Best in Place is a jQuery based AJAX Inplace-Editor that takes profit of RESTful server-side controllers to allow users to edit stuff with no need of forms. If the server have standard defined REST methods, particularly those to UPDATE your objects (HTTP PUT), then by adding the Javascript file to the application it is making all the fields with the proper defined classes to become user in-place editable.

The editor works by PUTting the updated value to the server and GETting the updated record afterwards to display the updated value.
**** D gem 'ffi', '1.9.0'
https://github.com/ffi/ffi

Ruby-FFI is a ruby extension for programmatically loading dynamic libraries, binding functions within them, and calling those functions from Ruby code. Moreover, a Ruby-FFI extension works without changes on Ruby and JRuby
**** D gem 'kgio', '2.8.0'
http://rubygems.org/gems/kgio

kgio provides non-blocking I/O methods for Ruby without raising exceptions on EAGAIN and EINPROGRESS. It is intended for use with the Unicorn and Rainbows! Rack servers, but may be used by other applications (that run on Unix-like platforms).
**** D gem 'raindrops', '0.11.0'
http://rubygems.org/gems/raindrops



Raindrops is a real-time stats toolkit to show statistics for Rack HTTP servers. It is designed for preforking servers such as Rainbows! and Unicorn, but should support any Rack HTTP server under Ruby 2.0, 1.9, 1.8 and Rubinius on platforms supporting POSIX shared memory. It may also be used as a generic scoreboard for sharing atomic counters across multiple processes.
**** gem "friendly_id", "~> 4.0.9”
https://github.com/norman/friendly_id

sjm@sjm-tj:~/nethd/tianji/tianjicom$ git grep -i Friendly_Id
Gemfile:gem "friendly_id", "~> 4.0.9"
app/models/company.rb:  friendly_id :abbrev


FriendlyId is the "Swiss Army bulldozer" of slugging and permalink plugins for Active Record. It lets you create pretty URLs and work with human-friendly strings as if they were numeric ids. 
**** gem "roo", '1.12.2'
https://github.com/Empact/roo

sjm@sjm-tj:~/nethd/tianji/tianjicom$ git grep -i Roo::
app/models/ce_question.rb:      excel = Roo::Excel.new("#{Rails.root}/db/subjects.xls")

Roo can access the contents of various spreadsheet files. It can handle * OpenOffice * Excel * Google spreadsheets * Excelx * LibreOffice * CSV
**** D gem 'tilt', '1.4.1'
https://github.com/rtomayko/tilt/

sjm@sjm-tj:~/nethd/tianji/tianjicom$ git grep -i tilt
Gemfile:gem 'tilt', '1.4.1'
app/assets/javascripts/jquery/jquery.KinSlideshow-1.2.1.min.js:eval((function(a,b){return a.replace(/\w+/g, function(ss){ return b[parseInt(ss, 36)]; }); })("(


Generic interface to multiple Ruby template engines
**** gem "galetahub-simple_captcha", '0.1.5', :require => "simple_captcha"
https://github.com/izzm/simple-captcha

sjm@sjm-tj:~/nethd/tianji/tianjicom$ git grep -i SimpleCaptcha
app/controllers/account/accounts_controller.rb:  include SimpleCaptcha::ControllerHelpers
app/controllers/events_controller.rb:  include SimpleCaptcha::ControllerHelpers
db/migrate/20130608173157_create_simple_captcha_data.rb:class CreateSimpleCaptchaData < ActiveRecord::Migration
sjm@sjm-tj:~/nethd/tianji/tianjicom$ git grep -i Simple_Captcha
Gemfile:gem "galetahub-simple_captcha", '0.1.5', :require => "simple_captcha"
app/controllers/account/accounts_controller.rb:    if simple_captcha_valid?
app/models/article.rb:  apply_simple_captcha :message => "请输入正确验证码"
app/models/event.rb:  apply_simple_captcha :message => "请输入正确验证码"
app/models/topic.rb:  apply_simple_captcha :message => "请输入正确验证码"
app/views/account/accounts/_get_sms_graph_captcha.slim:= show_simple_captcha
app/views/account/accounts/verify_code.html.erb:    <div id="simple_captcha" class="hide">
app/views/account/accounts/verify_code.html.erb:      <%= show_simple_captcha %>
app/views/account/accounts/verify_code.html.erb:  $('#real_code').attr('src', $('.simple_captcha_image img').attr('src'));
app/views/account/accounts/verify_code.html.erb:  $('#simple_captcha').load("/account/accounts/get_sms_graph_captcha",
app/views/account/accounts/verify_code.html.erb:  $('#real_code').attr('src', $('.simple_captcha_image img').attr('src'));
app/views/articles/new.html.erb:          <%= f.simple_captcha %>
app/views/events/_form.html.erb:        <%= f.simple_captcha %>
app/views/simple_captcha/_simple_captcha.erb:  .simple_captcha{border: 0 none; padding: 5px !important;margin-top: 5px;}
app/views/simple_captcha/_simple_captcha.erb:  .simple_captcha,
app/views/simple_captcha/_simple_captcha.erb:  .simple_captcha div{display: table;}
app/views/simple_captcha/_simple_captcha.erb:  .simple_captcha .simple_captcha_field,
app/views/simple_captcha/_simple_captcha.erb:  .simple_captcha .simple_captcha_image{
app/views/simple_captcha/_simple_captcha.erb:  .simple_captcha .simple_captcha_image{
app/views/simple_captcha/_simple_captcha.erb:  .simple_captcha .simple_captcha_image img{
app/views/simple_captcha/_simple_captcha.erb:  .simple_captcha .simple_captcha_label{font-size: 12px;}
app/views/simple_captcha/_simple_captcha.erb:  .simple_captcha .simple_captcha_field input{
app/views/simple_captcha/_simple_captcha.erb:<div class='simple_captcha'>
app/views/simple_captcha/_simple_captcha.erb:  <div class='simple_captcha_image'>
app/views/simple_captcha/_simple_captcha.erb:    <%= simple_captcha_options[:image] %>
app/views/simple_captcha/_simple_captcha.erb:  <div class='simple_captcha_field'>
app/views/simple_captcha/_simple_captcha.erb:    <%= simple_captcha_options[:field] %>
app/views/topics/_form.html.erb:    <%= f.simple_captcha %>
config/locales/lib/simple_captcha.yml:  simple_captcha:
db/migrate/20130608173157_create_simple_captcha_data.rb:    create_table :simple_captcha_data do |t|
db/migrate/20130608173157_create_simple_captcha_data.rb:    add_index :simple_captcha_data, :key, :name => "idx_key"
db/migrate/20130608173157_create_simple_captcha_data.rb:    drop_table :simple_captcha_data
spec/controllers/account/accounts_controller_spec.rb:        controller.stub(:simple_captcha_valid?).and_return(true)
spec/controllers/account/accounts_controller_spec.rb:        controller.stub(:simple_captcha_valid?).and_return(false)
sjm@sjm-tj:~/nethd/tianji/tianjicom$ 


Rails 3 support now! Simple Captcha is the simplest and a robust captcha plugin. Its implementation requires adding up a single line in views and in controllers/models.http://expressica.com/simple_captcha

**** gem "showbuilder",        "~> 0.0.15”
https://github.com/ery/showbuilder

sjm@sjm-tj:~/nethd/tianji/tianjicom$ nano gem_dependency.rb
sjm@sjm-tj:~/nethd/tianji/tianjicom$ git grep -i show_model
app/helpers/admin/show_builder_extension_helper.rb:    def show_model_table(models, itext_base = nil, &block)
app/helpers/admin/show_builder_extension_helper.rb:          contents << show_model_table_header(itext_base, &block)
app/helpers/admin/show_builder_extension_helper.rb:          contents << show_model_table_body(models, &block)
app/helpers/admin/show_builder_extension_helper.rb:    def show_model_form(models, options ={}, &block)
app/views/admin/email_backgrounds/_form.slim:= show_model_form [:admin, @email_template] do |form|
app/views/admin/email_backgrounds/get_preview.slim:= show_model_form [:admin, @email_template], :url => {:action => :preview}, :method => :post, :html => {:tar
app/views/admin/email_backgrounds/index.slim:= show_model_table @email_templates, :email_background_mongo do |row|
app/views/admin/email_backgrounds/templates/_base.slim:  = show_model_form current_model, url: send("admin_email_background_#{@model_name}_path", @email_backgr
app/views/admin/email_backgrounds/templates/_edus.slim:  = show_model_form email_edu, url: admin_email_background_edu_path(@email_background, email_edu), html:
app/views/admin/read_book/book_intergrations/_form.slim:= show_model_form [:admin, :read_book, @book_intergration] do |form|
app/views/admin/read_book/book_intergrations/index.slim:= show_model_table @book_intergrations do |row|
app/views/admin/read_book/books/_form.slim:= show_model_form [:admin, :read_book, @book] do |form|
app/views/admin/read_book/books/index.slim:= show_model_table @books do |row|
app/views/admin/read_book/books/show.slim:= show_model_view @book do |view|
app/views/admin/read_book/btags/index.slim:= show_model_table @btags do |row|
app/views/admin/read_book/reco_rules/_form.slim:= show_model_form [:admin, :read_book, @reco_rule] do |form|
app/views/admin/read_book/reco_rules/index.slim:= show_model_table @industries do |row|

A Rails View Helper. Base on Twitter Bootstrap v2.0.4. Fast show model/s as view, form, table.
*** zhuxiaowu

gem 'nokogiri', ‘1.6.0'
gem 'piet', ‘0.1.3'
gem 'wice_grid', ‘3.0.4'
gem "strip_attributes", “1.4.4"
gem 'gdata_19', '1.1.5'
gem 'hpricot', ‘0.8.6'
*** gem dependence
gems = `bundle show`
gems = gems.gsub("\n  * ", '!').gsub(")", '').gsub(' (', '!')
gems = gems[0, gems.length-1]
gems = gems.split('!')
gems = gems[1, gems.length]

gemlist = {}
gems.each_with_index do |g, i|
  gemlist[gems[i-1]] = [g]  if (i % 2).eql?(1)
end

gemlist.each do |k, v|
  ds = `gem dependency #{k} -v #{v.first}`
  if ds =~ /\n /
    ds = ds[0, ds.length-2].split("\n  ")
    gemlist[k] << ds[1,ds.length] if ds.length > 1
  end
end


irb(main):023:0> gemlist.each{|k, v| puts "#{k} => #{v}"}
actionmailer => ["3.2.15", ["actionpack (= 3.2.15)", "mail (~> 2.5.4)"]]
actionpack => ["3.2.15", ["activemodel (= 3.2.15)", "activesupport (= 3.2.15)", "builder (~> 3.0.0)", "erubis (~> 2.7.0)", "journey (~> 1.0.4)", "rack (~> 1.4.5)", "rack-cache (~> 1.2)", "rack-test (~> 0.6.1)", "sprockets (~> 2.2.1)", "tzinfo (~> 0.3.29, development)"]]
activemodel => ["3.2.15", ["activesupport (= 3.2.15)", "builder (~> 3.0.0)"]]
activerecord => ["3.2.15", ["activemodel (= 3.2.15)", "activesupport (= 3.2.15)", "arel (~> 3.0.2)", "tzinfo (~> 0.3.29)"]]
activeresource => ["3.2.15", ["activemodel (= 3.2.15)", "activesupport (= 3.2.15)"]]
activesupport => ["3.2.15", ["i18n (>= 0.6.4, ~> 0.6)", "multi_json (~> 1.0)"]]
acts_as_list => ["0.3.0", ["activerecord (>= 3.0)", "bundler (>= 1.0.0, development)", "rdoc (>= 0, development)", "sqlite3 (>= 0, development)"]]
ansi => ["1.4.3", ["detroit (>= 0, development)", "lemon (>= 0, development)", "qed (>= 0, development)"]]
arel => ["3.0.2", ["hoe (~> 2.13, development)", "minitest (~> 2.11, development)", "rdoc (~> 3.10, development)"]]
authlogic => ["3.3.0", ["activerecord (>= 3.2)", "activesupport (>= 3.2)", "bcrypt-ruby (>= 0, development)", "i18n (>= 0, development)", "rake (>= 0, development)", "scrypt (>= 0, development)", "sqlite3 (>= 0, development)", "timecop (>= 0, development)"]]
awesome_print => ["1.1.0", ["fakefs (>= 0.2.1, development)", "rspec (>= 2.6.0, development)"]]
axiom-types => ["0.0.5", ["bundler (>= 1.3.5, ~> 1.3, development)", "descendants_tracker (~> 0.0.1)", "ice_nine (~> 0.9)"]]
backports => ["3.3.5"]
best_in_place => ["2.1.0", ["capybara (~> 1.1.2, development)", "jquery-rails (>= 0)", "nokogiri (>= 0, development)", "rails (~> 3.1)", "rspec-rails (~> 2.8.0, development)"]]
bluepill => ["0.0.60", ["activesupport (>= 3.0.0)", "bundler (>= 1.0.10, development)", "daemons (<= 1.1.6, ~> 1.1.4)", "faker (~> 0.9, development)", "i18n (>= 0.5.0)", "rake (!= 0.9.0, development)", "rr (~> 1.0, development)", "rspec-core (~> 2.0, development)", "rspec-expectations (~> 2.0, development)", "state_machine (~> 1.1.0)", "yard (~> 0.7, development)"]]
bson => ["1.9.2"]
bson_ext => ["1.9.1", ["bson (~> 1.9.1)"]]
builder => ["3.0.4"]
bundler => ["1.3.4", ["ronn (~> 0.7.3, development)", "rspec (~> 2.11, development)"]]
cancan => ["1.6.10", ["rails (~> 3.0.9, development)", "rr (~> 0.10.11, development)", "rspec (~> 2.6.0, development)", "supermodel (~> 0.1.4, development)"]]
capistrano => ["2.15.5", ["highline (>= 0)", "mocha (= 0.9.12, development)", "net-scp (>= 1.0.0)", "net-sftp (>= 2.0.0)", "net-ssh (>= 2.0.14)", "net-ssh-gateway (>= 1.1.0)"]]
capybara => ["2.1.0", ["cucumber (>= 0.10.5, development)", "fuubar (>= 0.0.1, development)", "launchy (>= 2.0.4, development)", "mime-types (>= 1.16)", "nokogiri (>= 1.3.3)", "pry (>= 0, development)", "rack (>= 1.0.0)", "rack-test (>= 0.5.4)", "rake (>= 0, development)", "rspec (>= 2.2.0, development)", "selenium-webdriver (~> 2.0, development)", "sinatra (>= 0.9.4, development)", "xpath (~> 2.0)", "yard (>= 0.5.8, development)"]]
carrierwave => ["0.9.0", ["activemodel (>= 3.2.0)", "activesupport (>= 3.2.0)", "cucumber (~> 1.3.2, development)", "fog (>= 1.3.1, development)", "json (>= 1.7)", "mini_magick (>= 3.6.0, development)", "mysql2 (>= 0, development)", "rails (>= 3.2.0, development)", "rmagick (>= 0, development)", "rspec (~> 2.13.0, development)", "sham_rack (>= 0, development)", "timecop (>= 0, development)"]]
carrierwave-mongoid => ["0.6.1", ["carrierwave (< 0.10.0, >= 0.8.0)", "mini_magick (>= 0, development)", "mongoid (< 5.0, >= 3.0)", "mongoid-grid_fs (~> 1.3)", "pry (>= 0, development)", "rake (~> 10.0, development)", "rspec (~> 2.14, development)"]]
cells => ["3.8.8", ["actionpack (>= 3.0)", "haml (>= 0, development)", "minitest (>= 2.8.1, development)", "railties (>= 3.0)", "rake (>= 0, development)", "simple_form (>= 0, development)", "slim (>= 0, development)", "tzinfo (>= 0, development)"]]
celluloid => ["0.15.2", ["benchmark_suite (>= 0, development)", "guard-rspec (>= 0, development)", "rake (>= 0, development)", "rspec (>= 0, development)", "timers (~> 1.1.0)"]]
childprocess => ["0.3.9", ["ffi (>= 1.0.11, ~> 1.0)", "rake (~> 0.9.2, development)", "rspec (>= 2.0.0, development)", "yard (>= 0, development)"]]
chinese_pinyin => ["0.5.0"]
client_side_validations => ["3.2.5", ["coffee-script (>= 0, development)", "coveralls (>= 0, development)", "jquery-rails (>= 0, development)", "json (>= 0, development)", "m (>= 0, development)", "mocha (>= 0, development)", "rails (~> 3.2.0, development)", "shotgun (>= 0, development)", "sinatra (~> 1.0, development)", "sqlite3 (>= 0, development)", "thin (>= 0, development)"]]
client_side_validations-simple_form => ["2.1.0", ["client_side_validations (~> 3.2.5)", "coffee-script (>= 0, development)", "json (>= 0, development)", "m (>= 0, development)", "mocha (>= 0, development)", "rails (~> 3.2.0, development)", "shotgun (>= 0, development)", "simple_form (~> 2.1.0)", "sinatra (~> 1.0, development)", "thin (>= 0, development)"]]
coderay => ["1.0.9"]
coercible => ["0.2.0", ["backports (>= 3.1.0, ~> 3.0)", "descendants_tracker (~> 0.0.1)"]]
coffee-rails => ["3.2.2", ["coffee-script (>= 2.2.0)", "railties (~> 3.2.0)"]]
coffee-script => ["2.2.0", ["coffee-script-source (>= 0)", "execjs (>= 0)"]]
coffee-script-source => ["1.6.3"]
crack => ["0.4.1", ["safe_yaml (~> 0.9.0)"]]
daemons => ["1.1.6"]
database_cleaner => ["1.0.1"]
descendants_tracker => ["0.0.3", ["rake (~> 10.1.0, development)", "rspec (~> 2.13.0, development)", "yard (~> 0.8.6.1, development)"]]
diff-lcs => ["1.2.4", ["hoe (~> 3.6, development)", "hoe-bundler (~> 1.2, development)", "hoe-doofus (~> 1.0, development)", "hoe-gemspec2 (~> 1.1, development)", "hoe-git (~> 1.5, development)", "hoe-rubygems (~> 1.0, development)", "hoe-travis (~> 1.2, development)", "rake (~> 10.0, development)", "rdoc (~> 4.0, development)", "rspec (~> 2.0, development)", "rubyforge (>= 2.0.4, development)"]]
domain_name => ["0.5.15", ["bundler (>= 1.2.0, development)", "rake (>= 0.9.2.2, development)", "rdoc (>= 2.4.2, development)", "shoulda (>= 0, development)", "unf (< 1.0.0, >= 0.0.5)"]]
email-spy => ["0.0.5", ["gdata_19 (~> 1.1.5)", "httpclient (~> 2.2.5)", "mechanize (~> 2.5.1)", "nokogiri (~> 1.6.0)", "rspec (~> 2.11.0, development)"]]
equalizer => ["0.0.7", ["bundler (>= 1.3.5, ~> 1.3, development)"]]
erubis => ["2.7.0"]
eventmachine => ["1.0.3", ["bluecloth (>= 0, development)", "rake-compiler (~> 0.8.3, development)", "yard (>= 0.8.5.2, development)"]]
execjs => ["2.0.2", ["rake (>= 0, development)"]]
factory_girl => ["4.2.0", ["activesupport (>= 3.0.0)", "appraisal (~> 0.5.1, development)", "aruba (>= 0, development)", "bourne (>= 0, development)", "cucumber (~> 1.2.1, development)", "mocha (>= 0.12.8, development)", "rspec (~> 2.12.0, development)", "simplecov (>= 0, development)", "sqlite3 (>= 0, development)", "timecop (>= 0, development)", "yard (>= 0, development)"]]
factory_girl_rails => ["4.2.1", ["appraisal (~> 0.5.0, development)", "aruba (~> 0.5.1, development)", "cucumber (~> 1.2.1, development)", "factory_girl (~> 4.2.0)", "railties (>= 3.0.0)", "rake (>= 0, development)", "rspec (~> 2.11.0, development)"]]
faraday => ["0.8.8", ["multipart-post (~> 1.2.0)", "rake (>= 0, development)", "simplecov (>= 0, development)"]]
ffi => ["1.9.0", ["rake (>= 0, development)", "rake-compiler (>= 0.6.0, development)", "rspec (>= 0, development)", "rubygems-tasks (>= 0, development)"]]
formatador => ["0.2.4", ["rake (>= 0, development)", "shindo (>= 0, development)"]]
formtastic => ["2.2.1", ["BlueCloth (>= 0, development)", "actionpack (>= 3.0)", "ammeter (~> 0.2.5, development)", "appraisal (>= 0, development)", "colored (>= 0, development)", "hpricot (~> 0.8.3, development)", "rake (>= 0, development)", "rcov (~> 0.9.9, development)", "rspec-rails (~> 2.8.0, development)", "rspec_tag_matchers (>= 1.0.0, development)", "tzinfo (>= 0, development)", "yard (~> 0.6, development)"]]
friendly_id => ["4.0.10.1", ["activerecord (< 4.0, >= 3.0)", "ffaker (>= 0, development)", "globalize3 (>= 0, development)", "i18n (>= 0, development)", "maruku (>= 0, development)", "minitest (~> 4.4.0, development)", "mocha (~> 0.13.1, development)", "railties (< 4.0, >= 3.0, development)", "simplecov (>= 0, development)", "yard (>= 0, development)"]]
galetahub-simple_captcha => ["0.1.5"]
gdata_19 => ["1.1.5"]
git => ["1.2.6", ["rake (>= 0, development)", "rdoc (>= 0, development)", "test-unit (>= 0, development)"]]
grape => ["0.6.1", ["activesupport (>= 0)", "builder (>= 0)", "bundler (>= 0, development)", "grape-entity (>= 0.2.0, development)", "hashie (>= 1.2.0)", "maruku (>= 0, development)", "multi_json (>= 1.3.2)", "multi_xml (>= 0.5.2)", "rack (>= 1.3.0)", "rack-accept (>= 0)", "rack-mount (>= 0)", "rack-test (>= 0, development)", "rake (>= 0, development)", "rspec (~> 2.9, development)", "virtus (>= 1.0.0)", "yard (>= 0, development)"]]
grape-entity => ["0.3.0", ["activesupport (>= 0)", "bundler (>= 0, development)", "maruku (>= 0, development)", "multi_json (>= 1.3.2)", "rake (>= 0, development)", "rspec (~> 2.9, development)", "yard (>= 0, development)"]]
grape-swagger => ["0.6.0", ["bundler (> 1.0.0, development)", "grape (>= 0.2.0)", "jeweler (~> 1.8.4, development)", "kramdown (>= 0)", "pry (>= 0, development)", "rack-test (>= 0, development)", "rdoc (~> 3.12, development)", "rspec (>= 0, development)", "shoulda (>= 0, development)"]]
guard => ["2.2.3", ["bundler (>= 0, development)", "formatador (>= 0.2.4)", "listen (~> 2.1)", "lumberjack (~> 1.0)", "pry (>= 0.9.12)", "rspec (~> 2.14, development)", "thor (>= 0.18.1)"]]
guard-rspec => ["4.0.3", ["bundler (>= 1.3.5, development)", "guard (>= 2.1.1)", "launchy (>= 0, development)", "rake (>= 0, development)", "rspec (>= 0, development)", "rspec (~> 2.14)"]]
guard-spork => ["1.5.1", ["bundler (~> 1.0, development)", "childprocess (>= 0.2.3)", "guard (>= 1.1)", "guard-rspec (~> 1.0, development)", "rspec (~> 2.10, development)", "spork (>= 0.8.4)"]]
hashie => ["2.0.5", ["growl (>= 0, development)", "guard (>= 0, development)", "guard-rspec (>= 0, development)", "rake (~> 0.9.2, development)", "rspec (~> 2.5, development)"]]
hashr => ["0.0.22", ["rake (>= 0, development)", "test_declarative (>= 0.0.2, development)"]]
highline => ["1.6.20"]
hike => ["1.2.3", ["rake (>= 0, development)"]]
hpricot => ["0.8.6"]
httparty => ["0.12.0", ["json (~> 1.8)", "multi_xml (>= 0.5.2)"]]
httpclient => ["2.2.7"]
i18n => ["0.6.5", ["activesupport (>= 3.0.0, development)", "mocha (>= 0, development)", "sqlite3 (>= 0, development)", "test_declarative (>= 0, development)"]]
ice_nine => ["0.10.0", ["bundler (>= 1.3.5, ~> 1.3, development)"]]
jeweler => ["1.8.4", ["bluecloth (>= 0, development)", "bundler (~> 1.0)", "cucumber (~> 1.1.4, development)", "git (>= 1.2.5)", "rake (>= 0)", "rcov (>= 0, development)", "rdoc (>= 0, development)", "rdoc (>= 0)", "yard (~> 0.7.4, development)"]]
journey => ["1.0.4", ["hoe (~> 2.13, development)", "json (>= 0, development)", "minitest (~> 2.11, development)", "racc (>= 1.4.6, development)", "rdoc (~> 3.10, development)", "rdoc (~> 3.11, development)"]]
jquery-rails => ["2.0.2", ["railties (< 5.0, >= 3.2.0)", "thor (~> 0.14)"]]
json => ["1.8.0", ["permutation (>= 0, development)", "sdoc (~> 0.3.16, development)\n\nGem json_pure-1.8.0", "permutation (>= 0, development)", "rake (~> 0.9.2, development)", "sdoc (~> 0.3.16, development)"]]
kgio => ["2.8.0"]
kramdown => ["1.2.0", ["coderay (~> 1.0.0, development)", "stringex (~> 1.5.1, development)"]]
libnotify => ["0.8.2", ["ffi (>= 1.0.11)", "minitest (~> 4.7.4, development)", "minitest-libnotify (~> 0.2.2, development)", "simplecov (>= 0, development)", "yard (~> 0.8.6.1, development)"]]
listen => ["2.2.0", ["bundler (>= 1.3.5, development)", "celluloid (>= 0.15.2)", "rake (>= 0, development)", "rb-fsevent (>= 0.9.3)", "rb-inotify (>= 0.9)", "rspec (>= 0, development)", "rspec-retry (>= 0, development)"]]
lumberjack => ["1.0.4"]
macaddr => ["1.6.1", ["systemu (~> 2.5.0)"]]
mail => ["2.5.4", ["bundler (>= 1.0.3, development)", "mime-types (~> 1.16)", "rake (> 0.8.7, development)", "rdoc (>= 0, development)", "rspec (~> 2.12.0, development)", "treetop (~> 1.4.8)"]]
mechanize => ["2.5.1", ["domain_name (>= 0.5.1, ~> 0.5)", "hoe (~> 3.0, development)", "mime-types (>= 1.17.2, ~> 1.17)", "minitest (~> 2.11, development)", "net-http-digest_auth (>= 1.1.1, ~> 1.1)", "net-http-persistent (>= 2.5.2, ~> 2.5)", "nokogiri (~> 1.4)", "ntlm-http (>= 0.1.1, ~> 0.1)", "rdoc (~> 3.10, development)", "webrobots (>= 0.0.9, ~> 0.0)"]]
method_source => ["0.8.2", ["bacon (~> 1.1.0, development)", "rake (~> 0.9, development)"]]
mime-types => ["1.25", ["hoe (~> 3.7, development)", "hoe-bundler (~> 1.2, development)", "hoe-doofus (~> 1.0, development)", "hoe-gemspec2 (~> 1.1, development)", "hoe-git (~> 1.5, development)", "hoe-rubygems (~> 1.0, development)", "hoe-travis (~> 1.2, development)", "minitest (~> 5.0, development)", "rake (~> 10.0, development)", "rdoc (~> 4.0, development)", "rubyforge (>= 2.0.4, development)"]]
mini_magick => ["3.5.0", ["rake (>= 0, development)", "subexec (~> 0.2.1)", "test-unit (>= 0, development)"]]
mini_portile => ["0.5.2"]
mongo => ["1.9.1", ["bson (~> 1.9.1)"]]
mongoid => ["3.1.4", ["activemodel (~> 3.2)", "moped (~> 1.4)", "origin (~> 1.0)", "tzinfo (~> 0.3.22)"]]
mongoid-grid_fs => ["1.9.0", ["mime-types (~> 1.19)", "mongoid (~> 3.0)"]]
mono_logger => ["1.1.0", ["bundler (~> 1.3, development)", "minitest (~> 4.0, development)", "rake (>= 0, development)"]]
moped => ["1.5.1"]
multi_json => ["1.7.4", ["bundler (~> 1.0, development)"]]
multi_xml => ["0.5.5", ["bundler (~> 1.0, development)"]]
multipart-post => ["1.2.0"]
mysql2 => ["0.3.13", ["eventmachine (>= 0, development)", "rake (~> 0.9.3, development)", "rake-compiler (~> 0.8.1, development)", "rspec (~> 2.8.0, development)"]]
net-http-digest_auth => ["1.4", ["hoe (~> 3.6, development)", "minitest (~> 5.0, development)", "rdoc (~> 4.0, development)"]]
net-http-persistent => ["2.9", ["hoe (~> 3.6, development)", "minitest (~> 5.0, development)", "rdoc (~> 4.0, development)"]]
net-scp => ["1.1.2", ["mocha (>= 0, development)", "net-ssh (>= 2.6.5)", "test-unit (>= 0, development)"]]
net-sftp => ["2.1.2", ["mocha (>= 0, development)", "net-ssh (>= 2.6.5)", "test-unit (>= 0, development)"]]
net-ssh => ["2.7.0", ["mocha (>= 0, development)", "test-unit (>= 0, development)"]]
net-ssh-gateway => ["1.2.0", ["mocha (>= 0, development)", "net-ssh (>= 2.6.5)", "test-unit (>= 0, development)"]]
newrelic-grape => ["1.3.1", ["grape (>= 0)", "newrelic_rpm (>= 0)"]]
newrelic_moped => ["0.0.6", ["moped (>= 0)", "newrelic_rpm (~> 3.6.0)", "rake (>= 0, development)"]]
newrelic_rpm => ["3.6.6.147", ["minitest (~> 4.7.5, development)", "mocha (~> 0.13.0, development)", "rails (~> 3.2.13, development)", "rake (= 10.1.0, development)", "rdoc (>= 2.4.2, development)", "sdoc-helpers (>= 0, development)", "sequel (~> 3.46.0, development)", "sqlite3 (>= 0, development)"]]
nokogiri => ["1.6.0", ["hoe (~> 2.16, development)", "hoe-bundler (>= 1.1, development)", "hoe-debugging (>= 1.0.3, development)", "hoe-gemspec (>= 1.0, development)", "hoe-git (>= 1.4, development)", "mini_portile (~> 0.5.0)", "minitest (~> 2.2.2, development)", "racc (>= 1.4.6, development)", "rake (>= 0.9, development)", "rake-compiler (~> 0.8.0, development)", "rdoc (~> 3.10, development)", "rexical (>= 1.0.5, development)"]]
ntlm-http => ["0.1.1"]
oauth => ["0.4.7", ["actionpack (>= 2.3.5, development)", "curb (>= 0.6.6.0, development)", "em-http-request (>= 0.2.10, development)", "jeweler (>= 0, development)", "mocha (>= 0.9.8, development)", "rack (>= 1.0.0, development)", "rake (>= 0, development)", "typhoeus (>= 0.1.13, development)"]]
oauth2 => ["0.5.2", ["faraday (~> 0.7)", "multi_json (~> 1.0)", "multi_xml (>= 0, development)", "rake (>= 0, development)", "rdoc (>= 0, development)", "rspec (>= 0, development)", "simplecov (>= 0, development)", "yard (>= 0, development)"]]
omniauth => ["1.1.4", ["bundler (~> 1.0, development)", "hashie (< 3, >= 1.2)", "rack (>= 0)"]]
omniauth-oauth2 => ["1.0.0", ["oauth2 (~> 0.5.0)", "omniauth (~> 1.0)", "rack-test (>= 0, development)", "rspec (~> 2.7, development)", "simplecov (>= 0, development)", "webmock (>= 0, development)"]]
omniauth-weibo-oauth2 => ["0.3.0", ["omniauth (~> 1.0)", "omniauth-oauth2 (~> 1.0)"]]
origin => ["1.1.0"]
piet => ["0.1.3", ["ZenTest (>= 0, development)", "png_quantizator (>= 0)", "rspec (>= 0, development)"]]
png_quantizator => ["0.1.0", ["rspec (>= 0, development)"]]
polyglot => ["0.3.3"]
pry => ["0.9.12.2", ["bacon (~> 1.2, development)", "bond (~> 0.4.2, development)", "coderay (~> 1.0.5)", "guard (~> 1.3.2, development)", "method_source (~> 0.8)", "mocha (~> 0.13.1, development)", "open4 (~> 1.3, development)", "rake (~> 0.9, development)", "slop (~> 3.4)"]]
pry-nav => ["0.2.3", ["pry (~> 0.9.10)", "pry-remote (~> 0.1.6, development)"]]
quiet_assets => ["1.0.2", ["railties (< 5.0, >= 3.1)", "rake (>= 0, development)", "tzinfo (>= 0, development)"]]
rack => ["1.4.5", ["bacon (>= 0, development)", "memcache-client (>= 0, development)", "mongrel (>= 1.2.0.pre2, development)", "rake (>= 0, development)", "ruby-fcgi (>= 0, development)", "thin (>= 0, development)"]]
rack-accept => ["0.4.5", ["rack (>= 0.4)", "rake (>= 0, development)"]]
rack-cache => ["1.2", ["bacon (>= 0, development)", "dalli (>= 0, development)", "memcached (>= 0, development)", "rack (>= 0.4)"]]
rack-mount => ["0.8.3", ["racc (>= 0, development)", "rack (>= 1.0.0)", "rake (>= 0, development)", "rexical (>= 0, development)"]]
rack-protection => ["1.5.1", ["rack (>= 0)", "rack-test (>= 0, development)", "rspec (~> 2.0, development)"]]
rack-ssl => ["1.3.3", ["rack (>= 0)"]]
rack-test => ["0.6.2", ["rack (>= 1.0)"]]
rails => ["3.2.15", ["actionmailer (= 3.2.15)", "actionpack (= 3.2.15)", "activerecord (= 3.2.15)", "activeresource (= 3.2.15)", "activesupport (= 3.2.15)", "bundler (~> 1.0)", "railties (= 3.2.15)"]]
rails3-generators => ["1.0.0", ["bundler (>= 1.0.0, development)", "factory_girl (>= 0, development)", "rails (>= 3.0.0, development)", "railties (>= 3.0.0)", "rake (>= 0, development)", "test-unit (>= 0, development)"]]
rails_autolink => ["1.1.0", ["rails (> 3.1)"]]
railties => ["3.2.15", ["actionpack (= 3.2.15)", "activesupport (= 3.2.15)", "rack-ssl (~> 1.3.2)", "rake (>= 0.8.7)", "rdoc (~> 3.4)", "thor (< 2.0, >= 0.14.6)"]]
raindrops => ["0.11.0", ["aggregate (~> 0.2, development)", "io-extra (>= 1.2.3, ~> 1.2, development)", "posix_mq (~> 2.0, development)", "rack (~> 1.2, development)", "unicorn (>= 0.98, development)"]]
rake => ["10.1.0", ["minitest (~> 2.1, development)"]]
rb-fsevent => ["0.9.3", ["bundler (~> 1.0, development)", "guard-rspec (~> 1.2, development)", "rspec (~> 2.11, development)"]]
rb-inotify => ["0.9.2", ["ffi (>= 0.5.0)", "yard (>= 0.4.0, development)"]]
rdoc => ["3.12.2", ["ZenTest (~> 4, development)", "hoe (~> 3.5, development)", "json (~> 1.4)", "minitest (~> 4.3, development)", "racc (~> 1.4, development)", "rdoc (~> 3.10, development)"]]
redis => ["3.0.4", ["rake (>= 0, development)"]]
redis-activesupport => ["3.2.3", ["activesupport (~> 3.2.3)", "bundler (~> 1.1.rc, development)", "minitest (~> 2.8.0, development)", "mocha (~> 0.10.0, development)", "purdytest (~> 1.0.0, development)", "rake (~> 0.9.2.2, development)", "redis-store (~> 1.1.0)"]]
redis-namespace => ["1.3.0", ["rake (>= 0, development)", "redis (~> 3.0.0)", "rspec (>= 0, development)"]]
redis-objects => ["0.7.0", ["bacon (>= 0, development)", "redis (>= 3.0.2)", "redis-namespace (>= 1.2.0, development)"]]
redis-store => ["1.1.3", ["bundler (~> 1.1, development)", "git (~> 1.2.5, development)", "minitest (~> 2.8.0, development)", "mocha (~> 0.10.0, development)", "purdytest (~> 1.0.0, development)", "rake (~> 0.9.2, development)", "redis (>= 2.2.0)"]]
require_relative => ["1.0.3", ["minitest (>= 0, development)", "rocco (>= 0, development)"]]
resque => ["1.24.1", ["mono_logger (~> 1.0)", "multi_json (~> 1.0)", "redis-namespace (~> 1.2)", "sinatra (>= 0.9.2)", "vegas (~> 0.1.2)"]]
resque-dynamic-queues => ["0.8.1", ["json (>= 0, development)", "rack-test (~> 0.5.4, development)", "rake (>= 0, development)", "resque (~> 1.10)", "rspec (~> 2.5, development)"]]
resque-scheduler => ["2.0.1", ["bundler (>= 1.0.0, development)", "redis (>= 2.0.1)", "resque (>= 1.20.0)", "rufus-scheduler (>= 0)"]]
resque_mailer => ["2.2.4", ["actionmailer (>= 3.0)", "rspec (~> 2.6, development)", "yard (>= 0.6.0, development)"]]
rest-client => ["1.6.7", ["mime-types (>= 1.16)", "rspec (>= 0, development)", "webmock (>= 0.9.1, development)"]]
roo => ["1.12.2", ["google_drive (>= 0, development)", "jeweler (>= 0, development)", "nokogiri (>= 0)", "rubyzip (>= 0)", "spreadsheet (> 0.6.4)"]]
rspec => ["2.14.1", ["rspec-core (~> 2.14.0)", "rspec-expectations (~> 2.14.0)", "rspec-mocks (~> 2.14.0)"]]
rspec-core => ["2.14.7", ["ZenTest (~> 4.6, development)", "aruba (~> 0.5, development)", "cucumber (~> 1.1.9, development)", "flexmock (~> 0.9.0, development)", "mocha (~> 0.13.0, development)", "nokogiri (= 1.5.2, development)", "rake (~> 10.0.0, development)", "rr (~> 1.0.4, development)", "syntax (= 1.0.0, development)"]]
rspec-expectations => ["2.14.3", ["aruba (~> 0.5, development)", "cucumber (~> 1.1.9, development)", "diff-lcs (< 2.0, >= 1.1.3)", "rake (~> 10.0.0, development)"]]
rspec-mocks => ["2.14.4", ["aruba (~> 0.5, development)", "cucumber (~> 1.1.9, development)", "rake (~> 10.0.0, development)"]]
rspec-rails => ["2.14.0", ["ZenTest (= 4.9.0, development)", "actionpack (>= 3.0)", "activesupport (>= 3.0)", "ammeter (= 0.2.5, development)", "aruba (~> 0.4.11, development)", "capybara (>= 2.0.0, development)", "cucumber (~> 1.1.9, development)", "railties (>= 3.0)", "rake (~> 10.0.0, development)", "rspec-core (~> 2.14.0)", "rspec-expectations (~> 2.14.0)", "rspec-mocks (~> 2.14.0)"]]
ruby-ole => ["1.2.11.7"]
rubycas-client => ["2.3.9", ["actionpack (>= 0, development)", "activerecord (>= 0, development)", "activerecord-jdbcsqlite3-adapter (>= 0, development)", "activesupport (>= 0)", "bundler (>= 1.0, development)", "database_cleaner (>= 0, development)", "guard (>= 0, development)", "guard-rspec (>= 0, development)", "jeweler (>= 0, development)", "jruby-openssl (>= 0, development)", "json (>= 0, development)", "rake (>= 0, development)", "rspec (>= 0, development)", "simplecov (>= 0, development)", "sqlite3 (>= 0, development)"]]
rubyzip => ["0.9.9"]
rufus-scheduler => ["2.0.24", ["rake (>= 0, development)", "rspec (>= 2.7.0, development)", "tzinfo (>= 0.3.22)"]]
safe_yaml => ["0.9.7"]
sass => ["3.2.12", ["maruku (>= 0.5.9, development)", "yard (>= 0.5.3, development)"]]
sass-rails => ["3.2.6", ["railties (~> 3.2.0)", "sass (>= 3.1.10)", "tilt (~> 1.3)"]]
showbuilder => ["0.0.15"]
simple_form => ["2.1.0", ["actionpack (~> 3.0)", "activemodel (~> 3.0)"]]
sinatra => ["1.4.4", ["rack (~> 1.4)", "rack-protection (~> 1.4)", "tilt (>= 1.3.4, ~> 1.3)"]]
sitemap_generator => ["4.1.1", ["builder (>= 0)", "mocha (>= 0, development)", "nokogiri (>= 0, development)", "rspec (>= 0, development)"]]
slim => ["2.0.1", ["temple (~> 0.6.6)", "tilt (< 2.1, >= 1.3.3)"]]
slop => ["3.4.6", ["minitest (~> 5.0.0, development)", "rake (>= 0, development)"]]
spork => ["1.0.0rc3"]
spreadsheet => ["0.9.1", ["hoe (~> 2.13, development)", "rdoc (~> 3.10, development)", "ruby-ole (>= 1.0)"]]
sprockets => ["2.2.2", ["coffee-script (~> 2.0, development)", "coffee-script-source (~> 1.2.0, development)", "eco (~> 1.0, development)", "ejs (~> 1.0, development)", "execjs (~> 1.0, development)", "hike (~> 1.2)", "json (>= 0, development)", "multi_json (~> 1.0)", "rack (~> 1.0)", "rack-test (>= 0, development)", "rake (>= 0, development)", "tilt (!= 1.3.0, ~> 1.1)"]]
sqlite3 => ["1.3.7", ["hoe (~> 3.4, development)", "mini_portile (~> 0.2.2, development)", "rake-compiler (~> 0.8.2, development)", "rdoc (~> 3.10, development)"]]
state_machine => ["1.1.2", ["appraisal (~> 0.4.0, development)", "rake (>= 0, development)", "rcov (>= 0, development)"]]
strip_attributes => ["1.4.4", ["active_attr (~> 0.7, development)", "activemodel (< 5.0, >= 3.0)", "minitest (~> 4.7, development)", "minitest-matchers (~> 1.2, development)", "rake (~> 10.0, development)"]]
subexec => ["0.2.3", ["rake (>= 0, development)", "rspec (~> 2.7.0, development)"]]
systemu => ["2.5.2"]
temple => ["0.6.7", ["bacon (>= 0, development)", "rake (>= 0, development)", "tilt (>= 0, development)"]]
thor => ["0.18.1", ["bundler (~> 1.0, development)"]]
tilt => ["1.4.1", ["RedCloth (>= 0, development)", "asciidoctor (>= 0.1.0, development)", "bluecloth (>= 0, development)", "builder (>= 0, development)", "coffee-script (>= 0, development)", "contest (>= 0, development)", "creole (>= 0, development)", "erubis (>= 0, development)", "haml (>= 2.2.11, development)", "kramdown (>= 0, development)", "less (>= 0, development)", "liquid (>= 0, development)", "markaby (>= 0, development)", "maruku (>= 0, development)", "nokogiri (>= 0, development)", "radius (>= 0, development)", "rdiscount (>= 0, development)", "rdoc (>= 0, development)", "rdoc (>= 0, development)", "redcarpet (>= 0, development)", "sass (>= 0, development)", "wikicloth (>= 0, development)", "yajl-ruby (>= 0, development)"]]
timers => ["1.1.0", ["rake (>= 0, development)", "rspec (>= 0, development)"]]
tire => ["0.6.0", ["active_model_serializers (>= 0, development)", "activemodel (>= 3.0)", "activerecord (>= 3.0, development)", "activesupport (>= 0)", "ansi (>= 0)", "bson_ext (>= 0, development)", "bundler (~> 1.0, development)", "curb (>= 0, development)", "faraday (>= 0, development)", "hashr (~> 0.0.19)", "minitest (~> 2.12, development)", "mocha (~> 0.13, development)", "mongoid (~> 2.2, development)", "multi_json (~> 1.3)", "oj (>= 0, development)", "rake (>= 0)", "redis-persistence (>= 0, development)", "rest-client (~> 1.6)", "shoulda-context (>= 0, development)", "sqlite3 (>= 0, development)", "turn (~> 0.9, development)", "yajl-ruby (~> 1.0, development)"]]
treetop => ["1.4.15", ["activesupport (>= 0, development)", "i18n (~> 0.5.0, development)", "jeweler (>= 0, development)", "polyglot (>= 0)", "polyglot (>= 0.3.1)", "rake (>= 0, development)", "rr (~> 1.0, development)", "rspec (>= 2.0.0, development)"]]
turbo-sprockets-rails3 => ["0.3.6", ["railties (< 4.0.0, > 3.2.8)", "sprockets (>= 2.0.0)"]]
typhoeus => ["0.3.3", ["diff-lcs (>= 0, development)", "json (>= 0, development)", "mime-types (>= 0)", "rake (>= 0, development)", "rspec (~> 2.6, development)", "sinatra (>= 0, development)"]]
tzinfo => ["0.3.38"]
uglifier => ["2.1.2", ["bundler (~> 1.0, development)", "execjs (>= 0.3.0)", "jeweler (~> 1.8.3, development)", "multi_json (>= 1.0.2, ~> 1.0)", "rdoc (>= 3.11, development)", "rspec (~> 2.7, development)", "source_map (>= 0, development)"]]
unf => ["0.1.3", ["bundler (>= 1.2.0, development)", "rake (>= 0.9.2.2, development)", "rdoc (> 2.4.2, development)", "shoulda (>= 0, development)", "unf_ext (>= 0)"]]
unf_ext => ["0.0.6", ["bundler (>= 1.2, development)", "rake-compiler (>= 0.7.9, development)", "rdoc (> 2.4.2, development)", "shoulda (>= 0, development)"]]
unicorn => ["4.6.3", ["isolate (~> 3.2, development)", "kgio (~> 2.6)", "rack (>= 0)", "raindrops (~> 0.7)", "wrongdoc (~> 1.6.1, development)"]]
uuid => ["2.3.7", ["macaddr (~> 1.0)"]]
vegas => ["0.1.11", ["bacon (~> 1.1.0, development)", "mocha (~> 0.9.8, development)", "rack (>= 1.0.0)", "sinatra (~> 0.9.4, development)"]]
virtus => ["1.0.0", ["axiom-types (~> 0.0.5)", "coercible (~> 0.2)", "descendants_tracker (~> 0.0.1)", "equalizer (~> 0.0.7)"]]
webrobots => ["0.1.1", ["bundler (>= 1.2, development)", "nokogiri (>= 1.4.4, development)", "racc (>= 0, development)", "rake (>= 0.9.2.2, development)", "rdoc (> 2.4.2, development)", "shoulda (>= 0, development)"]]
weibo => ["0.0.14", ["crack (>= 0)", "hashie (>= 0)", "hashie (>= 0)", "httparty (>= 0)", "httparty (>= 0.5.2)", "jeweler (>= 0)", "oauth (~> 0.4.1)", "oauth (>= 0)", "thoughtbot-shoulda (>= 0, development)"]]
weibo2 => ["0.1.0", ["oauth2 (~> 0.5.1)", "rspec-rails (>= 0, development)"]]
weibo2_plugins => ["0.0.6", ["mocha (>= 0, development)", "oauth2 (~> 0.5.1)", "rspec (~> 2.3, development)", "typhoeus (= 0.3.3)", "weibo2 (~> 0.1.0)", "yard (~> 0.6.0, development)"]]
wice_grid => ["3.0.4", ["will_paginate (>= 3.0.pre2, development)"]]
will_paginate => ["3.0.4"]
will_paginate_mongoid => ["1.1.0", ["mongoid (>= 2.4)", "will_paginate (~> 3.0)"]]
xpath => ["2.0.0", ["nokogiri (~> 1.3)", "rake (>= 0, development)", "rspec (~> 2.0, development)", "yard (>= 0.5.8, development)"]]
yajl-ruby => ["1.1.0", ["activesupport (>= 0, development)", "json (>= 0, development)", "rake-compiler (>= 0.7.5, development)", "rspec (>= 2.0.0, development)"]]

** corp seo: url change to chinese name
** corp site map: 20140109
*** fp: http://192.168.3.4/new_companies/homepage/companyList.html
*** run: 
root@web1.env-40-9.dev.tianji.com:/tianji/web/current# RAILS_ENV=integ rake sitemap:generate_corp_site_map > s1.txt

root@web1.env-40-9.dev.tianji.com:/tianji/web/current# cat s1.txt 
total records: 9379 2014-01-15 10:09:17
== starting 0*501... 2014-01-15 10:09:17
== starting 1*501... 2014-01-15 10:09:17
== starting 2*501... 2014-01-15 10:09:17
== starting 3*501... 2014-01-15 10:09:18
== starting 4*501... 2014-01-15 10:09:18
== starting 5*501... 2014-01-15 10:09:18
== starting 6*501... 2014-01-15 10:09:18
== starting 7*501... 2014-01-15 10:09:18
== starting 8*501... 2014-01-15 10:09:18
== starting 9*501... 2014-01-15 10:09:19
== starting 10*501... 2014-01-15 10:09:19
== starting 11*501... 2014-01-15 10:09:19
== starting 12*501... 2014-01-15 10:09:19
== starting 13*501... 2014-01-15 10:09:19
== starting 14*501... 2014-01-15 10:09:19
== starting 15*501... 2014-01-15 10:09:19
== starting 16*501... 2014-01-15 10:09:19
== starting 17*501... 2014-01-15 10:09:19
== starting 18*501... 2014-01-15 10:09:19
= get data end 2014-01-15 10:09:19
= writing erb starting 2014-01-15 10:09:19
= writing erb B-1.html 2014-01-15 10:09:19
= writing erb B-2.html 2014-01-15 10:09:19
= writing erb B-3.html 2014-01-15 10:09:19
= writing erb B-4.html 2014-01-15 10:09:19
= writing erb B-5.html 2014-01-15 10:09:20
= writing erb H-1.html 2014-01-15 10:09:20
= writing erb H-2.html 2014-01-15 10:09:20
= writing erb D-1.html 2014-01-15 10:09:20
= writing erb J-1.html 2014-01-15 10:09:20
= writing erb X-1.html 2014-01-15 10:09:20
= writing erb S-1.html 2014-01-15 10:09:20
= writing erb S-2.html 2014-01-15 10:09:20
= writing erb S-3.html 2014-01-15 10:09:20
= writing erb S-4.html 2014-01-15 10:09:20
= writing erb T-1.html 2014-01-15 10:09:20
= writing erb W-1.html 2014-01-15 10:09:20
= writing erb V-1.html 2014-01-15 10:09:20
= writing erb Z-1.html 2014-01-15 10:09:20
= writing erb Z-2.html 2014-01-15 10:09:20
= writing erb G-1.html 2014-01-15 10:09:20
= writing erb G-2.html 2014-01-15 10:09:20
= writing erb L-1.html 2014-01-15 10:09:20
= writing erb Y-1.html 2014-01-15 10:09:20
= writing erb C-1.html 2014-01-15 10:09:20
= writing erb F-1.html 2014-01-15 10:09:20
= writing erb M-1.html 2014-01-15 10:09:20
= writing erb Q-1.html 2014-01-15 10:09:20
= writing erb K-1.html 2014-01-15 10:09:20
= writing erb E-1.html 2014-01-15 10:09:20
= writing erb R-1.html 2014-01-15 10:09:20
= writing erb N-1.html 2014-01-15 10:09:20
= writing erb A-1.html 2014-01-15 10:09:20
= writing erb P-1.html 2014-01-15 10:09:20
= writing erb I-1.html 2014-01-15 10:09:20
= writing erb O-1.html 2014-01-15 10:09:20
= writing erb U-1.html 2014-01-15 10:09:20
= write erb done 2014-01-15 10:09:20
end 2014-01-15 10:09:20

** corp1.2: merge corp 20140106
*** common function
*** merge
*** split
*** ?招聘的白名单
*** 相关使用位置的修改
雇员/粉丝/邮箱后缀
**** 前台
***** 可能认识的雇员、雇员职位分布、通过他们了解该公司、雇员擅长技能、雇员来自于、工作经验统计、男女比例、新入雇员、以往雇员、公司名片、公司搜索结果、公司名联想模块
***** 被合并公司跳转
**** 后台
**** 雇员/粉丝改变：需要同时处理主公司和合并公司
counter_cache字段不能更新： ActiveRecord::Base.connection.execute("update corps set followers_count = 4 where id = 162")
**** 认证：自动通过的处理
*** 外部接口：
**** 公司搜索
**** 公司雇员是否有开通招聘服务
