* freelancer
** cn
*** zhubajie.com
*** vikecn.com
** en
*** Elance.com
    排名：1,738
    说明：真正的大活所在地，全球第一接活网站。从身怀绝技的个人到上百人的外包公司都有从这里接活，体质完善，服务到位。
    不过对沟通要求高，我在这里接的那几个活客户很多都要求语音沟通，通过skype或电话。而且基本上需要你有国外的信用卡才能认证。
    会员费很高但也很灵活，网站提成固定在8%左右。E文扛的住的朋友一定要挖掘这片天空。这个网站上每月挣几万或十几万美元的人不在少数。

***     Getafreelancer.com
    排名：2,957
    说明：简称GAF，同样也是全球非常知名的接活网站。这里人个接活者居多，同时活的数额也相对少一些。一般在30-100$或100-300$左右，也是我最常接活的网站。
    对于想在国外接活的朋友来说，这里是第一片试验田。网站做的非常易用，结构简单，服务一流。会员分为免费会员，不需要会员费，接活的时候网站提成10%，而且基本上每月只能投15-20个标。
    同时也可成为金牌会员，会员费12$，接活的时候网站不提成，每月可以投150个标。推荐大家去这里发展。

***     Scriptlance.com
    排名：5,367
    说明：Scriptlance上网站开发和网站设计类的活居多。这个网站在美国本土很火，很受美国客户喜欢。网站也是有固定的提成费，接活的模式有一点不同。
    灵活性很高，客户在上面发项目也是非常灵活。这个网站个性鲜明，属于哪种你用过一次，觉得爽就会一直用，觉得不爽就再也不会理的哪种。

***     Getacoder.com
    排名：16,590
    说明：从这个网站的名字就能看出，这里开发类的项目居多。这个网站的模式感觉上就是抄Getafreelancer的，网站基本上差不多。不过，这个网站有一个最大的文化特色：
    这里的项目都很独特，大部分客户都没有具体的需要，都是有一些idea或一个大概的想法，想找coder来实现。
    所以项目本身需要你更多的参与讨论，来给客户出一个解决方案。这个网站的客户都很热情并且主动。这里的付费会员有大量的网站模板资源可以使用。
    有一点不太理想的就是这里项目更新并不快，沟通上不是很方便。

***     Ifreelance.com
    排名：32,611
    说明：这里的模式跟前面几个也不一样，发包者大多数是公司。网站结构上并不是像前面几个那么易用，接起活来有一点点麻烦。
    但是活更新比较快，大活小活都有。费用上不是特别明确，等待更多验证。
